export enum PhaseHistoryNote {
    SUBMIT_TOPIC_CREATED = 'Khởi tạo pha nộp đề tài',
    LECTURER_INITIATED = 'Giảng viên tạo đề đề tài',
    TOPIC_SUBMITTED = 'Đề tài đã được nộp',
    TOPIC_APPROVED = 'Đề tài đã được duyệt bởi ban chủ nhiệm',
    TOPIC_REJECTED = 'Đề tài bị từ chối',
    OPEN_REGISTRATION_STARTED = 'Bắt đầu pha mở đăng ký',
    TOPIC_PENDING_REGISTRATION = 'Đề tài chờ đăng ký',
    TOPIC_REGISTERED = 'Đề tài đã được đăng ký',
    TOPIC_FULL = 'Đề tài đã đủ số lượng đăng ký',
    TOPIC_CANCELLED = 'Đề tài bị hủy đăng ký',
    EXECUTION_STARTED = 'Bắt đầu pha thực hiện đề tài',
    TOPIC_IN_PROGRESS = 'Đề tài đang thực hiện',
    TOPIC_DELAYED = 'Đề tài bị trì hoãn',
    TOPIC_PAUSED = 'Đề tài bị tạm dừng',
    TOPIC_SUBMITTED_FOR_REVIEW = 'Đề tài đã nộp báo cáo hoàn thành',
    TOPIC_AWAITING_EVALUATION = 'Đề tài chờ đánh giá',
    COMPLETION_STARTED = 'Bắt đầu pha hoàn tất',
    TOPIC_GRADED = 'Đề tài đã được chấm điểm',
    TOPIC_REVIEWED = 'Đề tài đã được đánh giá lại',
    TOPIC_ARCHIVED = 'Đề tài đã được lưu trữ',
    TOPIC_REJECTED_FINAL = 'Đề tài bị hội đồng từ chối ',
    SYSTEM_ACTION = 'Thao tác hệ thống',
    STUDENT_REGISTERED = 'Sinh viên đăng ký đề tài',
    STUDENT_CANCELLED_REGISTRATION = 'Sinh viên hủy đăng ký đề tài',
    LECTURER_ASSIGNED = 'Giảng viên được phân công vào đề tài',
    LECTURER_CANCELLED_ASSIGNMENT = 'Giảng viên hủy phân công đề tài'
}
